Rename covariance to correlation
sdv-dev/Copulas pull request #346
Opened 2023-03-31 14:37 UTC by frances-h

Resolve #343

2023-03-31 20:07 UTC, amontanez24 approved these changes
LGTM!

2023-04-01 08:22 UTC, fealho requested changes
Looks good, I just don't think we should update the `_get_conditional_distribution` output name, since it actually outputs the covariance.

2023-04-01 08:22 UTC, fealho commented on copulas/multivariate/gaussian.py
> +                * correlation (numpy.array):
I think this method actually computes the covariance, since that's what the `multivariate_normal` needs.

2023-04-01 08:22 UTC, fealho commented on copulas/multivariate/gaussian.py
> +            means, correlation, columns = self._get_conditional_distribution(normal_conditions)
So this is cov as well.

2023-04-01 08:22 UTC, fealho commented on tests/unit/multivariate/test_gaussian.py
> +        means, correlation, columns = gm._get_conditional_distribution(conditions)
Here as well.

2023-04-03 19:27 UTC, fealho approved these changes
Thanks for addressing 👍

2023-04-03 19:38 UTC, merged