Move visualization functions to `plotly` and get rid of `matplotlib` dependency
sdv-dev/Copulas pull request #368
Opened 2023-10-13 16:56 UTC by fealho

Resolve #348.

2023-10-16 15:17 UTC, frances-h commented
Can you add some screenshots showing the new plots?

2023-10-16 15:40 UTC, fealho commented
> Can you add some screenshots showing the new plots?

@frances-h Added to the description.

2023-10-17 19:04 UTC, amontanez24 commented
Task linked: [CU-860qhuhh5 Copulas - Move visualization functions to `plotly` and get rid of `matplotlib` dependency #348](https://app.clickup.com/t/860qhuhh5)

2023-10-18 15:30 UTC, amontanez24 commented on copulas/visualization.py
> +        color_discrete_map={'Real': PlotConfig.DATACEBO_DARK},
Same here

2023-10-25 17:27 UTC, npatki commented
> > Can you add some screenshots showing the new plots?
> 
> @frances-h Added to the description.

@fealho they are not rendering for me. I think that if you upload a local ipynb notebook into Drive, then Google Colab won't render the graphics. Is it possible to create a notebook directly on Google Colab and run the code from a branch or something? Doing in Colab would be nice bc we can also verify the the interactivity that all plotly graphs come with.

2023-10-27 17:40 UTC, npatki requested changes
I'm leaving all my feedback here based on the notebook. 

### Plot Titles
Original issue had mentioned we should update any titles to accurately reflect what is being shown. I didn't see a title for any of the generated plots, we should add that.

I'm basing the proposed titles based off the SDMetrics visualizations, which is what we wanted to align to.

- `dist_1d`: `Data for column '<name>'`. If there is no name (eg. you're passing in a Series without a name, we could leave that out)
- `compare_1d`: `Real vs. Synthetic Data for column '<name>'` (again can leave name out if there is none)
- `scatter_2d`: `Data for columns '<name>' and '<name>'`
- `compare_2d`: `Real vs. Synthetic Data for columns '<name>' and '<name>'`
- `scatter_3d`: `Data for columns '<name>', '<name>' and '<name>'`
- `compare_3d`: `Real vs. Synthetic Data for columns '<name>', '<name>' and '<name>'`

### X and Y Axes Labels
For the 1D plots (`dist_1d` and `compare_1d`) the axes should be labeled. These can be the same as SDMetrics. (X-axis is `value` and Y-axis is `frequency`)

2023-10-31 17:19 UTC, frances-h approved these changes
Looks good!

2023-11-01 00:16 UTC, npatki approved these changes

2023-11-01 00:17 UTC, npatki commented
Approved the title and axes changes. Though we should probably update that first notebook as a sanity check.

2023-11-01 00:37 UTC, amontanez24 approved these changes

2023-11-08 12:58 UTC, merged