Only run unit and integration tests on oldest and latest python versions for macos
sdv-dev/Copulas pull request #406
Opened 2024-04-29 13:39 UTC by R-Palazzo

CU-86b07h928
Resolve #405

2024-04-29 13:39 UTC, sdv-team commented
Task linked: [CU-86b07h928 Copulas - Only run unit and integration tests on oldest and latest python versions for macos #405](https://app.clickup.com/t/86b07h928)

2024-04-29 15:23 UTC, amontanez24 approved these changes

2024-04-29 15:25 UTC, amontanez24 requested changes
Just one small change

2024-04-29 15:25 UTC, amontanez24 commented on pyproject.toml
> +    "scipy>=1.8.0;python_version<'3.10'",
it looks like version 1.7.3 of scipy has arm support

2024-04-29 16:42 UTC, amontanez24 approved these changes

2024-04-30 17:27 UTC, lajohn4747 approved these changes
Nit: Should we leave a comment about why th

2024-05-01 15:52 UTC, merged